"""Add files table

Revision ID: 0011c7158340
Revises: f885a31cf49a
Create Date: 2016-06-19 17:26:57.246484

"""

# revision identifiers, used by Alembic.
revision = '0011c7158340'
down_revision = 'f885a31cf49a'
branch_labels = None
depends_on = None

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('commit_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['commit_id'], ['commits.id'], name=op.f('fk_files_commit_id_commits')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files'))
    )
    op.create_index('filename_index', 'files', ['filename'], unique=False)
    op.create_index('status_index', 'files', ['status'], unique=False)
    op.add_column('commits', sa.Column('additions', sa.Integer(), nullable=True))
    op.add_column('commits', sa.Column('authored_at', sa.DateTime(), nullable=True))
    op.add_column('commits', sa.Column('committed_at', sa.DateTime(), nullable=True))
    op.add_column('commits', sa.Column('deletions', sa.Integer(), nullable=True))
    op.create_index('authored_at_index', 'commits', ['authored_at'], unique=False)
    op.create_index('committed_at_index', 'commits', ['committed_at'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('committed_at_index', table_name='commits')
    op.drop_index('authored_at_index', table_name='commits')
    op.drop_column('commits', 'deletions')
    op.drop_column('commits', 'committed_at')
    op.drop_column('commits', 'authored_at')
    op.drop_column('commits', 'additions')
    op.drop_index('status_index', table_name='files')
    op.drop_index('filename_index', table_name='files')
    op.drop_table('files')
    ### end Alembic commands ###
