"""Add some extra indexes

Revision ID: 9d098b8cd7a0
Revises: 2fb094745389
Create Date: 2016-07-18 13:40:28.055080

"""

# revision identifiers, used by Alembic.
revision = '9d098b8cd7a0'
down_revision = '2fb094745389'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_orgs_name'), 'orgs', ['name'])
    op.create_unique_constraint('unique_repo_name_per_org', 'repos', ['name', 'org_id'])
    op.create_unique_constraint(op.f('uq_teams_name'), 'teams', ['name'])
    op.create_unique_constraint(op.f('uq_users_name'), 'users', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_name'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_teams_name'), 'teams', type_='unique')
    op.drop_constraint('unique_repo_name_per_org', 'repos', type_='unique')
    op.drop_constraint(op.f('uq_orgs_name'), 'orgs', type_='unique')
    ### end Alembic commands ###
