"""Add external ids

Revision ID: f885a31cf49a
Revises: 
Create Date: 2016-06-19 11:03:38.115834

"""

# revision identifiers, used by Alembic.
revision = 'f885a31cf49a'
down_revision = None
branch_labels = None
depends_on = None

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commits', sa.Column('added_at', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True))
    op.add_column('commits', sa.Column('sha', postgresql.BYTEA(length=40), nullable=False))
    op.create_unique_constraint(op.f('uq_commits_sha'), 'commits', ['sha'])
    op.add_column('orgs', sa.Column('added_at', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True))
    op.add_column('orgs', sa.Column('ext_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq_orgs_ext_id'), 'orgs', ['ext_id'])
    op.add_column('repos', sa.Column('added_at', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True))
    op.add_column('repos', sa.Column('ext_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq_repos_ext_id'), 'repos', ['ext_id'])
    op.add_column('teams', sa.Column('added_at', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True))
    op.add_column('teams', sa.Column('ext_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq_teams_ext_id'), 'teams', ['ext_id'])
    op.add_column('users', sa.Column('added_at', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True))
    op.add_column('users', sa.Column('ext_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq_users_ext_id'), 'users', ['ext_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_ext_id'), 'users', type_='unique')
    op.drop_column('users', 'ext_id')
    op.drop_column('users', 'added_at')
    op.drop_constraint(op.f('uq_teams_ext_id'), 'teams', type_='unique')
    op.drop_column('teams', 'ext_id')
    op.drop_column('teams', 'added_at')
    op.drop_constraint(op.f('uq_repos_ext_id'), 'repos', type_='unique')
    op.drop_column('repos', 'ext_id')
    op.drop_column('repos', 'added_at')
    op.drop_constraint(op.f('uq_orgs_ext_id'), 'orgs', type_='unique')
    op.drop_column('orgs', 'ext_id')
    op.drop_column('orgs', 'added_at')
    op.drop_constraint(op.f('uq_commits_sha'), 'commits', type_='unique')
    op.drop_column('commits', 'sha')
    op.drop_column('commits', 'added_at')
    ### end Alembic commands ###
